### ISSUE TITLE
Add .get method?

### ISSUE THREAD

**Issue by ludwigschubi** [nftstorage/ipfs-cluster#2]
Would be cool if there would be a .get method to read items from the cluster

**Comment by alanshaw** [comment]
The [cluster API](https://cluster.ipfs.io/documentation/reference/api/) has no "get" method but if you turn on the [IPFS proxy](https://cluster.ipfs.io/documentation/reference/proxy/) you can just use the `.get` method of the [`ipfs-http-client`](https://www.npmjs.com/package/ipfs-http-client).

**Comment by ludwigschubi** [comment]
For the principle of encapsulation and to hide exactly what you were explaining, i will add a .get method to my fork of this lib :)
