### ISSUE TITLE
Use commonjs export syntax

### ISSUE THREAD

**Issue by ludwigschubi** [nftstorage/ipfs-cluster#3]
I am using typescript and my commonjs compiled code can not import this package. During runtime it throws the error:
```
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Users/ludwigschubert/ipfs-shex-server/node_modules/@nftstorage/ipfs-cluster/index.js
require() of ES modules is not supported.
```

Are there plans to become interoperable with commonjs? As the below diagram shows commonjs export would work with both import syntaxes:
https://miro.medium.com/max/700/1*3cI3YvzG0HakM7VCaxtbfA.png

Maybe this goes hand-in-hand with adding typescript compilation for this package?

**Comment by alanshaw** [comment]
This is not on the roadmap as this module is designed for workers and/or the browser. Looks like that error is an old Node.js error and might be resolved by using a newer version.

**Comment by vaultec81** [comment]
Can this support be added? The ESModule situation is an absolute mess across typescript, normal JS, nodeJs, react TS, ts-node, etc, etc. Works with standard nodeJs, not with typescript..
