### ISSUE TITLE
Peers are not viewed in the JS API

### ISSUE THREAD

**Issue by lk2684753** [nftstorage/ipfs-cluster#30]
When using this, we wanted to know how all the nodes in the cluster were connected, but we didn't find an API for viewing peers.

**Comment by dchoi27** [comment]
Hey there, could you clarify what you're looking for? Once this lands, will this satisfy what you're looking for? https://github.com/nftstorage/nft.storage/issues/644

**Comment by dchoi27** [comment]
Hey there - closing for now, let us know if getting the peer IDs published (comment above) doesn't fix.
