### ISSUE TITLE
Unable to use with NodeJS

### ISSUE THREAD

**Issue by brickpop** [nftstorage/ipfs-cluster#46]
Despite the description on the Readme:

> it can be run in Node.js if required web APIs are added to the global environment

It seems as if the NPM package cannot be used on NodeJS v16 (shims applied):

<img width="717" alt="image" src="https://user-images.githubusercontent.com/4456749/176717384-c0b5e35e-9fd1-4edf-ac4b-9e9c5ede47bd.png">

Thank you

**Comment by vasco-santos** [comment]
Hi @brickpop 

This package is built for browser environment but it should be supported in Node. Did you add the code specified in Readme https://github.com/nftstorage/ipfs-cluster#using-in-nodejs ?

Can you share the code if so?

**Comment by brickpop** [comment]
Ok, so the problem is with vanilla CommonJS code. Adapting to this will not work, even with the shims applied.

```js
const fetch = require('@web-std/fetch')
const { FormData } = require('@web-std/form-data')
const { File, Blob } = require('@web-std/file')

Object.assign(global, { fetch, File, Blob, FormData })

const {Cluster} = require("@nftstorage/ipfs-cluster");
```

However, renaming the file to `*.mjs` and using ES module import syntax, works.
I wonder if the readme could clarify this, because otherwise, the instructions feel unrelated to the default Node use case. 
Thank you
