### ISSUE TITLE
the cid can't view in broswer by method of add

### ISSUE THREAD

**Issue by chengpengjava** [nftstorage/ipfs-cluster#47]
Hello Team,I used the method of add,I want to save file,and then I succeded, but if file's size exceed several hundred KB will fail,I don't know the reason and how to solve it.My code is following:
![image](https://user-images.githubusercontent.com/33616855/177490207-0e02a329-7f7b-405a-836d-1b4017d3381d.png)
![image](https://user-images.githubusercontent.com/33616855/177490435-2025e550-580f-4e13-be1a-936454661098.png)
![image](https://user-images.githubusercontent.com/33616855/177490528-5b198c27-c001-490a-8f91-af3f7d79c483.png)
I used koa-body to get the file in http request,finally every file I can get the cid,but some cid I can see http://.../ipfs/${cid} but some fail,I found those failed cid's file exceed several hundred KB,I don't know if it's the file size

**Comment by vasco-santos** [comment]
Hi @chengpengjava 

Are you running a docker image of ipfs cluster? ipfs-cluster image uses nginx which by default limits maximum upload size. You can read more about how to tweak this in https://www.tecmint.com/limit-file-upload-size-in-nginx/

**Comment by chengpengjava** [comment]
> Hi @chengpengjava
> 
> Are you running a docker image of ipfs cluster? ipfs-cluster image uses nginx which by default limits maximum upload size. You can read more about how to tweak this in https://www.tecmint.com/limit-file-upload-size-in-nginx/

Yes,I used docker image of ipfs cluster.I have solved this problem by following:
![image](https://user-images.githubusercontent.com/33616855/187624927-6ba497ff-8946-4e5d-a33b-9e04433e7e69.png)
I changed ipfs's version v0.10.0 to v0.14.0 and then I don't have this problem anymore
